**Project Title**

Customer Churn Prediction Model

**Problem Statement**

Customer retention is a critical challenge in the telecommunications industry, where acquiring new customers is significantly more expensive than retaining existing ones.

**Proposed Solution**

Here is the proposed solution workflow:

1. Data Preprocessing & Cleaning

2. Feature Engineering & Transformation

3. Data Splitting & Handling Class Imbalance

4. Model Selection & Training

5. Model Evaluation & Interpretation

**Dataset Description**

1.	customerID: A unique ID predicting each customer (e.g., 7590-VHVEG).
2.	gender: Whether the customer is male or female (male, female).
3.	SeniorCitizen: Indicates if the customer is a senior citizen (1 for Yes, 0 for No).
4.	Partner: Whether the customer has a partner or not (Yes, No).
5.	Dependents: Whether the customer has dependents or not (Yes, No).
6.	tenure: Number of months the customer has stayed with the company.
7.	PhoneService: Whether the customer has phone service (Yes, No).
8.	MultipleLines: Whether the customer has multiple lines (Yes, No, No phone service).
9.	InternetService: Customer’s internet service provider (DSL, fiber optic, No).
10.	OnlineSecurity: Whether the customer has online security service (Yes, No, No internet service).
11.	OnlineBackup: Whether the customer has online backup service (Yes, No, No internet service).
12.	DeviceProtection: Whether the customer has device protection service (Yes, No, No internet service).
13.	TechSupport: Whether the customer has tech support service (Yes, No, No internet service).
14.	StreamingTV: Whether the customer streams TV (Yes, No, No internet service).
15.	StreamingMovies: Whether the customer streams movies (Yes, No, No internet service).
16.	Contract: The contract term of the customer (Month-to-month, One year, Two year).
17.	PaperlessBilling: Whether the customer has paperless billing or not (Yes, No).
18.	PaymentMethod: Customer’s payment method (Electronic check, Mailed check, Bank transfer (automatic), Credit card (automatic)).
19.	MonthlyCharges: The amount charged to the customer monthly.
20.	TotalCharges: The total amount charged to the customer over their tenure (Note: May contain string spaces for new customers with tenure = 0).
21.	Churn: Whether the customer left within the last month (Yes or No).

In [ ]:
pip install xgboost

**Import Libraries**

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import joblib

**Load Dataset**

In [7]:
df = pd.read_csv('Telco_Customer_Churn.csv')

**Perform EDA**

-Dataset Inspection

In [5]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,NaN,0.0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0.0,No,No,34,Yes,No,DSL,Yes,...,Yes,NaN,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,NaN,No,No,2,Yes,No,NaN,Yes,...,No,NaN,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0.0,No,No,45,No,No phone service,NaN,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0.0,NaN,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0.0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,NaN,0.0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0.0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1.0,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0.0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [8]:
df.sample(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
5016,4140-WJAWW,Female,0.0,No,No,5,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Credit card (automatic),19.85,108.05,Yes
5971,9800-OUIGR,Male,0.0,Yes,Yes,66,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),20.00,1374.2,No
3108,5056-FIMPT,Female,0.0,No,Yes,43,Yes,No,Fiber optic,Yes,...,No,Yes,Yes,Yes,One year,Yes,Credit card (automatic),106.00,4532.3,No
2610,5202-IVJNU,Female,0.0,No,Yes,39,No,No phone service,DSL,No,...,Yes,No,No,No,Month-to-month,No,Credit card (automatic),30.10,1131.3,Yes
4239,6481-LXPWL,Male,0.0,Yes,Yes,56,No,No phone service,DSL,No,...,Yes,No,No,No,One year,Yes,Credit card (automatic),36.10,1971.5,No
201,8544-GOQSH,Female,0.0,No,No,14,Yes,No,Fiber optic,No,...,No,Yes,No,No,Month-to-month,Yes,Credit card (automatic),80.05,1112.3,No
4686,8024-XNAFQ,Female,1.0,No,No,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,No,Yes,Two year,Yes,Bank transfer (automatic),107.40,7748.75,No
1848,7190-XHTWJ,Female,0.0,No,No,38,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,19.30,755.5,No
3867,4922-CVPDX,Female,0.0,Yes,No,26,Yes,No,DSL,No,...,Yes,No,Yes,Yes,Two year,Yes,Credit card (automatic),73.50,1905.7,No
436,4980-URKXC,Male,0.0,Yes,No,36,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Bank transfer (automatic),20.85,720.05,No

In [9]:
df.shape

(7043, 21)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7039 non-null   str
 2   SeniorCitizen     7040 non-null   float64
 3   Partner           7040 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7041 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7041 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7041 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(1), str(18)
memory usage: 1.1 MB

In [11]:
df.dtypes

customerID              str
gender                  str
SeniorCitizen       float64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [12]:
df.isnull().sum()

customerID          0
gender              4
SeniorCitizen       3
Partner             3
Dependents          0
tenure              0
PhoneService        2
MultipleLines       0
InternetService     2
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         2
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [16]:
df.select_dtypes(include=['number']).columns.tolist()

['SeniorCitizen', 'tenure', 'MonthlyCharges']

In [17]:
df.select_dtypes(include=['string']).columns.tolist()

['customerID',
 'gender',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'TotalCharges',
 'Churn']

In [19]:
df.select_dtypes(include=['string']).columns.tolist()

['customerID',
 'gender',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'TotalCharges',
 'Churn']

In [24]:
for col in df.columns:
    print(f"\n{"*"*40}")
    print(f"COLUMN: {col}")
    print(f"{"*"*40}")
    print(df[col].value_counts(dropna=False))

****************************************
COLUMN: customerID
****************************************
customerID
7590-VHVEG    1
5575-GNVDE    1
3668-QPYBK    1
7795-CFOCW    1
9237-HQITU    1
             ..
6840-RESVB    1
2234-XADUH    1
4801-JZAZL    1
8361-LTMKD    1
3186-AJIEK    1
Name: count, Length: 7043, dtype: int64

****************************************
COLUMN: gender
****************************************
gender
Male      3555
Female    3484
NaN          4
Name: count, dtype: int64

****************************************
COLUMN: SeniorCitizen
****************************************
SeniorCitizen
0.0    5898
1.0    1142
NaN       3
Name: count, dtype: int64

****************************************
COLUMN: Partner
****************************************
Partner
No     3638
Yes    3402
NaN       3
Name: count, dtype: int64

****************************************
COLUMN: Dependents
****************************************
Dependents
No     4933
Yes    2110
Name: count, dtype: int64

****************************************
COLUMN: tenure
****************************************
tenure
1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: count, Length: 73, dtype: int64

****************************************
COLUMN: PhoneService
****************************************
PhoneService
Yes    6359
No      682
NaN       2
Name: count, dtype: int64

****************************************
COLUMN: MultipleLines
****************************************
MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

****************************************
COLUMN: InternetService
****************************************
InternetService
Fiber optic    3096
DSL            2419
No             1526
NaN               2
Name: count, dtype: int64

****************************************
COLUMN: OnlineSecurity
****************************************
OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

****************************************
COLUMN: OnlineBackup
****************************************
OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

****************************************
COLUMN: DeviceProtection
****************************************
DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

****************************************
COLUMN: TechSupport
****************************************
TechSupport
No                     3471
Yes                    2044
No internet service    1526
NaN                       2
Name: count, dtype: int64

****************************************
COLUMN: StreamingTV
****************************************
StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

****************************************
COLUMN: StreamingMovies
****************************************
StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

****************************************
COLUMN: Contract
****************************************
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

****************************************
COLUMN: PaperlessBilling
****************************************
PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64

****************************************
COLUMN: PaymentMethod
****************************************
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

****************************************
COLUMN: MonthlyCharges
****************************************
MonthlyCharges
20.05     61
19.85     45
19.95     44
19.90     44
19.70     43
          ..
72.00      1
108.35     1
63.10      1
44.20      1
78.70      1
Name: count, Length: 1585, dtype: int64

****************************************
COLUMN: TotalCharges
****************************************
TotalCharges
20.2      11
          11
19.75      9
19.9       8
20.05      8
          ..
1990.5     1
7362.9     1
346.45     1
306.6      1
6844.5     1
Name: count, Length: 6531, dtype: int64

****************************************
COLUMN: Churn
****************************************
Churn
No     5174
Yes    1869
Name: count, dtype: int64

**Observations**
- This dataset has 7043 rows and 21 columns
- Other columns have the correct data type except the Totalcharges column
- Missing values exist in 6 columns
- There are no duplicate rows in the dataset
- Some columns, such as CustomerID, Gender, & Tenure, did not have the correct naming convention
- There are 11 blank entries in the Total charges column, which made the data type change from float to object

-Data Cleaning

In [25]:
df['gender'] = df['gender'].fillna("Female")
df['SeniorCitizen'] = df['SeniorCitizen'].fillna(df['SeniorCitizen'].mode()[0])
df['Partner'] = df['Partner'].fillna(df['Partner'].mode()[0])
df['PhoneService'] = df['PhoneService'].fillna("No")
df['InternetService'] = df['InternetService'].fillna("No")
df['TechSupport'] = df['TechSupport'].fillna(df['TechSupport'].mode()[0])
df['TotalCharges'] = df['TotalCharges'].replace({" ": "0.0"}).astype(float)

In [26]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [27]:
df.dtypes

customerID              str
gender                  str
SeniorCitizen       float64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
Churn                   str
dtype: object

In [28]:
df.rename(columns={'customerID': 'CustomerID', 'gender': 'Gender', 'tenure': 'Tenure'}, inplace=True)

In [29]:
df.columns

Index(['CustomerID', 'Gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'Tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [ ]:
df['TotalCharges'].value_counts(dropna=False)

-Data visualization

In [ ]:
df['Churn'].value_counts().plot(kind='pie', autopct='%1.1f%%', colors=['blue', 'red'], explode=(0, 0.05))
plt.title('Churn Rate')
plt.show()

**Observation**
- The chart indicates that about 73.5% of the customers were active subscribers, whereas 26.5% of them left.

In [ ]:
sns.countplot(data=df, x='Contract', hue='Churn')
plt.title('Churn by Contract Type')
plt.show()

In [ ]:
sns.countplot(data=df, x='PaymentMethod', hue='Churn')
plt.xticks(rotation=45)
plt.title('Churn by Payment Method')
plt.show()

**Technical Support Utilization**

In [ ]:
plt.figure(figsize=(6, 4))
sns.countplot(data=df, x='TechSupport', hue='Churn')
plt.title('Churn by Tech Support Usage')
plt.show()

In [ ]:
plt.figure(figsize=(6, 4))
sns.countplot(data=df, x='Gender', hue='Churn')
plt.title('Churn by Gender')
plt.show()

In [ ]:
encoders = {}

for column in df:
    label_encoder = LabelEncoder()
    df[column] = label_encoder.fit_transform(df[column])
    encoders[column] = label_encoder

In [ ]:
plt.figure(figsize = (14, 10))
cut_upper = np.triu(df.corr())
sns.heatmap(df.corr(), annot=True, cmap = "coolwarm", fmt = ".2f", mask = cut_upper)
plt.title("Correlation Matrix")
plt.show()

In [ ]:
for col in df.columns:
    print(f"\n{"="*40}")
    print(f"COLUMN: {col}")
    print(f"{"="*40}")
    print(df[col].value_counts(dropna=False))

In [ ]:
df_ml = df.drop('CustomerID', axis=1)

In [ ]:
# To drop a particular column
X = df_ml.drop('Churn', axis=1)
y = df_ml['Churn']

In [ ]:
## To Standardize Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
rf_model = RandomForestClassifier(random_state=42)

# Train model
rf_model.fit(X_train, y_train)

# Predictions
rf_pred = rf_model.predict(X_test)

# Evaluation
print("========== Random Forest ==========")
print("Accuracy:", accuracy_score(y_test, rf_pred))
print("Precision:", precision_score(y_test, rf_pred))
print("Recall Score:", recall_score(y_test, rf_pred))
print("F1 Score:", f1_score(y_test, rf_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, rf_pred))

print("\nClassification Report")
print(classification_report(y_test, rf_pred))

In [ ]:
lr_model = LogisticRegression(max_iter=1000, random_state=42)

# Train model
lr_model.fit(X_train, y_train)

# Predictions
lr_pred = lr_model.predict(X_test)

# Evaluation
print("========== Logistic Regression ==========")
print("Accuracy:", accuracy_score(y_test, lr_pred))
print("Precision:", precision_score(y_test, lr_pred))
print("Recall Score:", recall_score(y_test, lr_pred))
print("F1 Score:", f1_score(y_test, lr_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, lr_pred))

print("\nClassification Report")
print(classification_report(y_test, lr_pred))

In [ ]:
# Save Model

In [ ]:
# Saving the Random Forest model
joblib.dump(lr_model, 'cusomer_churn_model.pkl')

In [ ]:
# Conclusion